export const popupFrames = [
    {
        id: 'rice',
        description: 'nightmarket.items.rice.popupDesc',
        width: '200px',
        height: 'auto',
        class: 'stall-wrapper-pork-rice',
        imgclass:'stall-pork-rice',
        imgurl:'/tjd103/SurvivalGuide/rice-mask-group.png',
        imgalt:'braised-pork-stall',
    },
    {
        id: 'tofu',
        description: 'nightmarket.items.tofu.popupDesc',
        width: '200px',
        height: 'auto',
        class: 'stall-wrapper-sticky-tofu',
        imgclass:'stall-sticky-tofu',
        imgurl:'/tjd103/SurvivalGuide/tofu-mask-group.png',
        imgalt:'sticky-tofu',
    },
    {
        id: 'bubble',
        description: 'nightmarket.items.bubble.popupDesc',
        width: '200px',
        height: 'auto',
        class: 'stall-wrapper-bubble-tea',
        imgclass:'stall-bubble-tea',
        imgurl:'/tjd103/SurvivalGuide/bubble-mask-group.png',
        imgalt:'bubble-tea',
    },
    {
        id: 'sausage',
        description: 'nightmarket.items.sausage.popupDesc',
        width: '200px',
        height: 'auto',
        class: 'stall-wrapper-sausage',
        imgclass:'stall-sausage',
        imgurl:'/tjd103/SurvivalGuide/sausage-mask-group.png',
        imgalt:'sausage',
    },
    {
        id: 'oil',
        description: 'nightmarket.items.oil.popupDesc',
        width: '200px',
        height: 'auto',
        class: 'stall-wrapper-oil',
        imgclass:'stall-oil',
        imgurl:'/tjd103/SurvivalGuide/oil-mask-group.png',
        imgalt:'oil',
    },
    {
        id: 'chicken',
        description: 'nightmarket.items.chicken.popupDesc',
        width: '200px',
        height: 'auto',
        class: 'stall-wrapper-chicken',
        imgclass:'stall-chicken',
        imgurl:'/tjd103/SurvivalGuide/chicken-mask-group.png',
        imgalt:'fried-chicken',
    },
    {
        id: 'game-dice',
        description: 'nightmarket.items.dice.popupDesc',
        width: '200px',
        height: 'auto',
        class: 'game-wrapper-dice',
        imgclass:'game-dice',
        imgurl:'/tjd103/SurvivalGuide/dice-mask-group.png',
        imgalt:'game-dice',
    },
    {
        id: 'game-prawning',
        description: 'nightmarket.items.prawning.popupDesc',
        width: '200px',
        height: 'auto',
        class: 'game-wrapper-prawning',
        imgclass:'game-prawning',
        imgurl:'/tjd103/SurvivalGuide/prawning-mask-group.png',
        imgalt:'game-prawning',
    },
    {
        id: 'game-ring-toss',
        description: 'nightmarket.items.ring-toss.popupDesc',
        width: '200px',
        height: 'auto',
        class: 'game-wrapper-ring-toss',
        imgclass:'game-ring-toss',
        imgurl:'/tjd103/SurvivalGuide/ring-toss-mask-group.png',
        imgalt:'game-ring-toss',
    },
]


export const infoFrames = [
    {
        id: 'food-introduction-rice',
        mainImg: '/tjd103/SurvivalGuide/rice1.jpg',
        title: 'nightmarket.items.rice.title',
        subTitle: 'nightmarket.items.rice.subTitle',
        text: 'nightmarket.items.rice.fullText',
        subImg1: '/tjd103/SurvivalGuide/rice2.jpg',
        subImg2: '/tjd103/SurvivalGuide/rice3.jpg',
        subImg3: '/tjd103/SurvivalGuide/rice4.jpg',
        subImg4: '/tjd103/SurvivalGuide/rice5.jpg',

    },
    {
        id: 'food-introduction-tofu',
        mainImg: '/tjd103/SurvivalGuide/tofu1.jpg',
        title: 'nightmarket.items.tofu.title',
        subTitle: 'nightmarket.items.tofu.subTitle',
        text: 'nightmarket.items.tofu.fullText',
        subImg1: '/tjd103/SurvivalGuide/tofu2.jpg',
        subImg2: '/tjd103/SurvivalGuide/tofu3.jpg',
        subImg3: '/tjd103/SurvivalGuide/tofu4.jpg',
        subImg4: '/tjd103/SurvivalGuide/tofu5.jpg',
    },
    {
        id: 'food-introduction-bubble-tea',
        mainImg: '/tjd103/SurvivalGuide/bubble_tea1.png',
        title: 'nightmarket.items.bubble.title',
        subTitle: 'nightmarket.items.bubble.subTitle',
        text: "nightmarket.items.bubble.fullText",
        subImg1: '/tjd103/SurvivalGuide/bubble_tea2.jpg',
        subImg2: '/tjd103/SurvivalGuide/bubble_tea3.jpg',
        subImg3: '/tjd103/SurvivalGuide/bubble_tea4.jpg',
        subImg4: '/tjd103/SurvivalGuide/bubble_tea5.jpg',
    },
    {
        id: 'food-introduction-sausage',
        mainImg: '/tjd103/SurvivalGuide/sausage1.jpg',
        title: 'nightmarket.items.sausage.title',
        subTitle: 'nightmarket.items.sausage.subTitle',
        text: "nightmarket.items.sausage.fullText",
        subImg1: '/tjd103/SurvivalGuide/sausage2.jpg',
        subImg2: '/tjd103/SurvivalGuide/sausage3.jpg',
        subImg3: '/tjd103/SurvivalGuide/sausage4.jpg',
        subImg4: '/tjd103/SurvivalGuide/sausage5.jpg',
    },
    {
        id: 'food-introduction-oil',
        mainImg: '/tjd103/SurvivalGuide/oil1.jpg',
        title: 'nightmarket.items.oil.title',
        subTitle: 'nightmarket.items.oil.subTitle',
        text: "nightmarket.items.oil.fullText",
        subImg1: '/tjd103/SurvivalGuide/oil2.jpg',
        subImg2: '/tjd103/SurvivalGuide/oil3.jpg',
        subImg3: '/tjd103/SurvivalGuide/oil4.jpg',
        subImg4: '/tjd103/SurvivalGuide/oil5.jpg',
    },
    {
        id: 'food-introduction-chicken',
        mainImg: '/tjd103/SurvivalGuide/chicken1.jpg',
        title: 'nightmarket.items.chicken.title',
        subTitle: 'nightmarket.items.chicken.subTitle',
        text: "nightmarket.items.chicken.fullText",
        subImg1: '/tjd103/SurvivalGuide/chicken2.jpg',
        subImg2: '/tjd103/SurvivalGuide/chicken3.jpg',
        subImg3: '/tjd103/SurvivalGuide/chicken4.jpg',
        subImg4: '/tjd103/SurvivalGuide/chicken5.jpg',
    },
    {
        id: 'game-introduction-dice',
        mainImg: '/tjd103/SurvivalGuide/dice1.png',
        title: 'nightmarket.items.dice.title',
        subTitle: 'nightmarket.items.dice.subTitle',
        text: "nightmarket.items.dice.fullText",
        subImg1: '/tjd103/SurvivalGuide/dice2.png',
        subImg2: '/tjd103/SurvivalGuide/dice3.png',
        buttonText: 'nightmarket.items.dice.buttonText'
    },
    {
        id: 'game-introduction-prawning',
        mainImg: '/tjd103/SurvivalGuide/prawning1.png',
        title: 'nightmarket.items.prawning.title',
        subTitle: 'nightmarket.items.prawning.subTitle',
        text: "nightmarket.items.prawning.fullText",
        subImg1: '/tjd103/SurvivalGuide/prawning2.png',
        subImg2: '/tjd103/SurvivalGuide/prawning3.jpg',
        buttonText: 'nightmarket.items.prawning.buttonText'
    },
    {
        id: 'game-introduction-ring-toss',
        mainImg: '/tjd103/SurvivalGuide/ringtoss1.png',
        title: 'nightmarket.items.ring-toss.title',
        subTitle: 'nightmarket.items.ring-toss.subTitle',
        text: "nightmarket.items.ring-toss.fullText",
        subImg1: '/tjd103/SurvivalGuide/ringtoss2.png',
        subImg2: '/tjd103/SurvivalGuide/ringtoss3.jpg',
        buttonText: 'nightmarket.items.ring-toss.buttonText'
    },
    {
        id:'map-api',
        mainImg: '/tjd103/SurvivalGuide/taiwan_image2_nobg.png',
        subImg1: '/tjd103/SurvivalGuide/tw_north.png',
        subImg2: '/tjd103/SurvivalGuide/tw_west.png',
        subImg3: '/tjd103/SurvivalGuide/tw_south.png',
        subImg4: '/tjd103/SurvivalGuide/tw_east.png',
    },
]